spring:
  application:
    name=assess
  datasource:
    url: jdbc:h2:mem:asses
    username: sa
    password: pass
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
springdoc:
  openapi:
    api-docs:
      path: /api-docs
      enabled: true
    swagger-ui:
      path: /swagger-ui.html
      enabled: true